---
title: "About Chad (Chungil Chae)"
description: |
  Introduction and basic information about Chad
author:
  - name: Chungil Chae
    url: https://chadchae.github.io
    affiliation: Wenzhou-Kean University
    affiliation_url: https://wku.edu.cn/en/faculty/chungil-chae-chad-ph-d/
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  distill::distill_article:
    self_contained: true
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Updated Nov 21, 2019

[Download PDF](https://chadchae.github.io/chadchaekor/img/chadcv.pdf)

# Chungil Chae (Chad)

**331W College Ave, APT 305, State College, PA 16801**
**(814) 880-5200 | chadchae@gmail.com**

## Current Employment
Post-Doctoral Scholar in the Applied Cognitive Science Lab within the College of Information Sciences and Technology at Penn State since 2018 Fall.

## Previous Employment
- Graduate assistant, Department of Learning and Performance Systems, Pennsylvania State University, 2013-2015.

- Assistant product manager, KCPMED, 2011-2012.

- Junior level consultant, Interwiz HR Consulting, 2010.
- 
- Graduate assistant, Human Resource Development, Indiana State University, 2008-2010.

- Market researcher, One-Tech Vision, 2004-2007.

## Education
- *Doctor of Philosophy*, Dual title degree in Workforce Education & 
Development and Comparative and International Education, Pennsylvania 
State University, August 2018. Dissertation: *Typology of knowledge-sharing intention in multinational companies: Cross-national comparative research with latent class analysis.* 
Available at https://etda.libraries.psu.edu/catalog/15009czc176 

- *Master of Science,* Human Resource Development, College of Engineering, Indiana State University, December 2010. Thesis: Co-author collaboration network: 2010 AHRD Conference symposium papers.* Slides related to this thesis are available at https://www.slideshare.net/chadchae/hrd685-presentation-interesting-version             

- *Bachelor of Business*, Business Administration, College of Business, Chung-Ang University, August 2004.

### Certificate
- Certificate of Achievement, DAT204x: Introduction to R Programming from edX, https://s3.amazonaws.com/verify.edx.org/downloads/46878a3e6d014f5eb779f1049afa979a/Certificate.pdf                    

- Certificate of Achievement, The Data Scientist's Toolbox from Coursera, https://www.coursera.org/account/accomplishments/certificate/LCK8SKDTFT             

- Certificate of Completion, 2009, 2010: Facilitation Skill Workshop, Indiana State University                                         
## Awards
- Highly Commended Paper Award for *Comparing HRD research's semantic structure between U.S. and Korea: A keyword network analysis approach*. Presentation at the University Forum for Human Resource Development Annual Conference, Nottingham, England, 2019.

- Outstanding Paper in the 2018 Emerald Literati Awards for *Intervention Research and Its Influence on Nonintervention Research in Human Resource Development* published in European Journal of Training and Development.

- Cutting Edge Paper Award, Academy of Human Resource Development, 2018. Suh, B., Li, B., Chae, C., & Han, S. (2018). *Organizational support on knowledge sharing: a moderated mediation model of job characteristics and organizational citizenship behavior.* Paper presented at the 2017 Academy of Human Resource Development International Research Conference in the Americas, San Antonio, Texas.

- Service Award, Korean Academy of Human Resource Development in America, 2016.

- Cutting Edge Paper Award, Academy of Human Resource Development, 2016. *Mapping the HRD knowledge: Keyword network perspective*. Paper presented at the meeting of 2016 Academy of Human Resource Development International Research Conference in the Americas, Jacksonville, Florida. The same paper won Best Korean graduate student paper award, Korean Academy of Human Resource Development in America, 2016.

- International Korean Student Scholarship, Pennsylvania State University, 2012.

## Publications
### Refereed journals
Lee, J. H., Kim, S., **Chae, C.,** & Lee, J. (2019) Career growth opportunity on turnover intention: The mediating role of organizational commitment in multinational corporations. *International Journal of Human Resource Studies*, 9(4), 1-18. doi:10.5296/ijhrs.v9i4.15245

Passmore, D. L., & **Chae, C.** (2019). Potential for meta-scientific inquiry to improve the usefulness of HRD research outcomes for practice. *Advances in Developing Human Resources, 21*(4), 409-420. doi: 10.1177/1523422319870173

**Chae, C.,** Yoon, S. W., Jo, S., & Han, S. (2019). Structural determinants of human resource development research collaboration networks: A social network analysis of publications between 1990 to 2014. *Performance Improvement Quarterly*, (Early view). doi: 10.1002/piq.21314

Lee, J. & **Chae, C**. (2019). Differences and multi-dimensionality of career success in Korean employees: A topic modeling approach. *The Journal of the Korea Contents Association, 19*(6), 58-71.

Fusar-Poli, P., Solmi1, M., Brondino, N., Davies, C., **Chae, C.,** Politi, P., Borgwardt S., Lawrie, S. M., Parnas, J., & Mcguire, P. (2019). Transdiagnostic psychiatry: A systematic review. *World Psychiatry, 18*(2), 192-207. doi:10.1002/wps.20631

Han, S, **Chae, C**, & Passmore, D. L. (2019) Social network analysis and social capital in human resource development research: A practical introduction to R use. *Human Resource Development Quarterly, 30*(2), 219-243. doi:10.1002/hrdq.21341

Han, S., Yoon, D., Suh, B., Li, B., & **Chae, C**. (2019). Organizational support on knowledge sharing: a moderated mediation model of job characteristics and organizational citizenship behavior. *Journal of Knowledge Management*, *23*(4), 687-704. doi:10.1108/JKM-03-2018-0213

Passmore, D. L., Baker, R. M. & **Chae, C**. (2019), Networks for performance. *Performance Improvement*, *58*(3), 20-25. doi:10.1002/pfi.21838

Passmore, D. L., **Chae, C**., Borkovskaya, V., Baker, R., & Yim J. (2019). Severity of U.S. construction worker injuries, 2015-2017. *E3S Web of Conferences*, *97*, 06038. doi:10.1051/e3sconf/20199706038

Passmore, D. L., **Chae, C**., Kustikova, Y., Baker, R. M., & Yim, J. (2018). An exploration of text mining of narrative reports of injury incidents to assess risk. *MATEC Web of Conferences*, *251*, 06020. doi:10.1051/matecconf/201825106020

Kim, S., Lee, S., & **Chae, C**. (2018). Research trends analysis in community network for sustainable RHRD. *The Korean Journal of Human Resource Development Quarterly*, *20*(3), 265-298. doi:10.18211/kjhrdq.2018.20.3.010

Han, H., Kim, Y., Kim, S., Cho, Y., & **Chae, C**. (2018). Looking into the labyrinth of gender inequality: Women physicians in academic medicine. *Medical Education*, *52*(10), 1083-1095. doi:10.1111/medu.13682

Han, S., **Chae, C**., Han, S. J., & Yoon, S. W. (2017). Conceptual organization and identity of HRD: Analyses of evolving definitions, influence, and connections, *Human Resource Development Review*, *16*(3), 294-319. doi: 10.1177/1534484317719822

Han, S., **Chae, C**., Macko, P., & Park, W. (2017). How virtual team leaders cope with creativity challenges. *European Journal of Training and Development*, *41*(3), 261-276. doi:EJTD-10-2016-0073

Park, S., & **Chae, C**. (2017). Intervention research and its influence on nonintervention research in human resource development. *European Journal of Training and Development*, *41*(5), 410-433. doi:10.1108/EJTD-08-2016-0062

Bonafini, F. C., **Chae, C**., Park, E. & Jablokow, K. W. (2017). How much does student engagement with videos and forums in a MOOC affect their achievement? *Online Learning*, *21*(4), 223-240. Retrieved May 16, 2019 from https://www.learntechlib.org/p/183772/

**Chae, C**., Han, S., & Kim, J. (2017). Research trends in HRD (2006-2015): A keyword network analysis of articles in AHRD journals. *The Korean Journal of Human Resource Development Quarterly*, *19*(1) 99-127. doi:10.18211/kjhrdq.2017.19.1.004

### Conference proceedings, presentations, lectures, workshops, and posters
Ritter, F.E., Dixon, M., **Chae, C.**, Garrison, C. (12 October 2019) Declarative to Procedural (D2P) Nursing Trauma Care Tutors. A talk in IST department.

Ritter, F. E., Stager, S., Brener, M., **Chae, C**., Weyhrauch, P., Niehaus, J., & McDermott, A. (2019). Maintenance training under uncertainty: Expanding smart tutoring to support skill learning and retention. ONR Cognitive Science of Learning Program Review

Harford, J., & **Chae, C.** (2019 August). Helping and hindering factors for inmates meeting the challenges for successful community reentry. *Academy of Management Proceedings*, *1*. https://doi.org/10.5465/AMBPP.2019.13372abstract

Yim, J., **Chae, C**., & Croweder, C. (2019 June). *Comparing HRD research semantic structure between U.S. and Korea: A keyword network analysis approach*. Presentation at the University Forum for Human Resource Development Annual Conference 2019, Nottingham, England.

Passmore, D., Park, M., & **Chae, C**. (2019 June). *National accounting for human capital*. Presentation at the University Forum for Human Resource Development Annual Conference 2019, Nottingham, England.

**Chae, C**. (2019). *Using research skills beyond publishing*. Presentation for emerging leaders in career and technical education, organization development, and human resource development. Pennsylvania State University, University Park, PA.

Passmore, D., Chae, C., Borkovskaya, V., Baker, R. M., & Yim, J. (2019 April). *Severity of U.S. construction worker injuries, 2015-2017*. Paper presented at XXII International Scientific Conference on Advanced in Civil Engineering: Construction - The Formation of Living Environment 2019, Tashkent, Uzbekistan.

**Chae, C**. (2019, May). *How to organize R projects*. Presented at "Starting with R" workshop, Penn State University, University Park, PA.

Passmore, D., **Chae, C.**, & Baker, R. M. (2019 February). *Selectivity and specificity of automated decisions based on p-value calculations: A study design.* Poster presented at the 2019 Academy of Human Resource Development International Research Conference in the Americas, Louisville, Kentucky.

Lee, J., Ahn, J., **Chae, C.,** & Yim, J. (2019 February). *A sequence analysis of changing perceptions of decent work among Korean employees.* Paper presented at the 2019 Academy of Human Resource Development International Research Conference in the Americas, Louisville, Kentucky.

Passmore, D., Baker, R. M., & **Chae C.** (2018 May). *Can you trust your algorithm?* Paper presented at the EdTech 2018 meeting of the Irish Learning and Technology Association, Carlow, Ireland.

Suh, B., Li, B., **Chae, C**., & Han, S. (2018). *Organizational support on knowledge sharing: a moderated mediation model of job characteristics and organizational citizenship behavior.* Paper presented at the 2017 Academy of Human Resource Development International Research Conference in the Americas, San Antonio, Texas.

Han, H., Kim, Y., Cho, Y., **Chae, C.,** & Kim, S. (2017). Female physicians' lived experience in career development in Korean academic medicine. *Academy of Management Proceedings, 2017*(1), 12200. doi:10.5465/AMBPP.2017.12200abstract

**Chae, C.** (2017). *Basic statistics with R*. Lecture and workshop at Lao Statistics Bureau sponsored by the Korea Statistics Promotion Institute, Vientiane, Lao People's Democratic Republic.

**Chae, C.** (2017). *Open-source research tools and social network analysis for HR/HRD researchers*. Presentation sponsored by The Korean Association of Human Resource Development, Chung-Ang University, Korea.

**Chae, C.** (2017). *Social network analysis for HR/HRD professionals*. Workshop presented at the 2017 Academy of Human Resource Development International Research Conference in the Americas, San Antonio, Texas, and sponsored by Korea Academy of Human Resource Development in America.

Baker, R. M., Baker, F., Passmore, D., & **Chae, C.** (2017 March) *Mixed methods models and use in Academy of Human Resource Development publications*. Paper presented at the 2017 Academy of Human Resource Development International Research Conference in the Americas, San Antonio, Texas.

**Chae, C.,** Al-Khadhuri, J., Passmore, D., Baker, R. M., & Turner, J. (2017 March). *Structural model of topics in Academy of Human Resource Development journals, 1990-2015*. Paper presented at the 2017 Academy of Human Resource Development International Research Conference in the Americas, San Antonio, Texas. doi:10.6084/m9.figshare.4725577.v1

**Chae, C**., You, J., Passmore, L., & Baker, R. (2017, March). *Social network analysis for human resource development/organization development professionals.* Invited pre-conference workshop at the 2017 Academy of Human Resource Development International Research Conference in the Americas, San Antonio, Texas.

**Chad, C.,** Han, S., & Kim, J. (2017). *Research trends in adult education (2006-2015): A topic modeling analysis.* Paper presented at the meeting of 2017 Adult Education Research Conference, Norman, Oklahoma.

**Chae, C.** (2016). A series of lectures and workshops on social network analysis applications in organizational practice. Presented at Universidad ECCI, Bogota, Columbia.

Kim, Y., **Chae, C**., Macko, P., Spencer, M., & Cassie, G. (2016, February). *Defining workforce development profession and professionals: A content analysis of occupation.* Paper presented at the meeting of 2016 Academy of Human Resource Development International Research Conference in the Americas, Jacksonville, Florida.

**Chae, C**., Al-Khadhuri, J., Park, W., Harford, J., & Luke, T. (2016, February). *Revealing socio-cultural complexity of knowledge sharing motif among Korean and U.S. companies*. Paper presented at the meeting of 2016 Academy of Human Resource Development International Research Conference in the Americas, Jacksonville, Florida.

**Chae, C**., Yang, H., & Yoon, S. (2016, February). *Mapping the HRD knowledge: Keyword network perspective*. Paper presented at the meeting of 2016 Academy of Human Resource Development International Research Conference in the Americas, Jacksonville, Florida.

**Chae, C.**, Al-Khadhuri, J., Yang, H., Park, W (2016, February). *A study on research trends in the recent human resource development: Topic modeling approach*. Paper presented at the meeting of 2016 Academy of Human Resource Development International Research Conference in the Americas, Jacksonville, Florida.

**Chae, C.** (2015). *Stochastic social network analysis*. Presented at Korean R User Conference, Korea.

Nicholas, J., Mohammad, H. A., **Chae, C.**, & Mohd, R. (2015, November). *School-to-work experiential learning and outcomes for students in career and technical education*. Paper presented at the meeting of the Career and Technical Research and Professional Development Conference, New Orleans, Louisiana.

**Chae, C.,** Yoon, S., & Jo, S. (2015, February). *Structural determinants of human resource development research collaboration networks: Social network perspectives*. Paper presented at the meeting of 2015 Academy of Human Resource Development International Research Conference in the Americas, St. Louis, Missouri.

Passmore, D., Baker, R., **Chae, C**., Fu, I., & Donahue, W. (2014, March). *Hybrid course design.* Presented at 2014 Symposium for Teaching and Learning with Technology, University Park, PA.

Eversole, B., & **Chae, C.** (2010, February). *Decision-making styles of CEOs: A new model for human relations problems*. Paper presented at 2010 Academy of Human Resource Development International Research Conference in the Americas, Knoxville, Tennessee.

**Chae, C.** (2009). *Kirkpatrick's four levels evaluation model*. Presentation to the Wabash Valley SHRM chapter, Terre Haute, IN.

### Book chapters
**Chae. C.**, Suh. B., Han. S., & Han. H. (2018). Enhancing learner-driven informal learning in a virtual practice community: The Massive Open Online Course (MOOC) as a learning solution for professional development. In Keengwe. (Eds.), *Handbook of research on digital content, mobile learning and technology integration models in teacher education*. (pp. 207-226). Harrisburg, PA: IGI Global. doi:10.4018/978-1-5225-2953-8.ch011

### Non-refereed journals
Nicholas, J., **Chae, C.**, Mohammed H. A., Zulkifli, R. M., & Passmore, D. (2015). School-to-work revisited: Did work-based learning experiences improve prospects for students in career and technical education? *SSRN Electronic Journal.* doi:10.2139/ssrn.2703854

## Teaching
### Instructor & co-instructor
- *Co-instructor,* WF ED 540, Data Analysis in Workforce Education and Development, Department of Learning and Performance System, Pennsylvania State University, 2018 Fall.

### Guest lecturer in university courses
- Working distance: application of collaboration tool, Pennsylvania State University, 2019 Fall
- Basic statistics and data analysis, Kongju University, Korea, 2018 Spring.
- Big data analysis for humanities, Chung-Nam University, Korea, 2017 Fall.
- Data analysis, Hankyung University, Korea, 2017 Fall.
- Computational social science method: social network analysis, Hanyang University, Korea, 2017 Fall.
- History and evolution of human resource development, University of Georgia, Athens, GA 2016 Fall.
- Knowledge structure analysis in R: Pathfinder network, Pennsylvania State University, University Park, PA, 2015 Fall.

### Instructional designer & teaching assistant
- *Teaching assistant*, WF ED 540, Data analysis, Pennsylvania State University, University Park, PA, 2014-2016 Fall.

- *Instructional designer*, ENGR 409, Leadership in organizations, Pennsylvania State University, University park, PA, 2015 fall & 2016 Spring.

- *Instructional designer,* course design and development in Master of Professional Studies in Organization Development and Change (MPS-OD&C) program.

- *Teaching assistant & instructional designer*, ADTED 552, Participatory action research in education, Pennsylvania State University, University park, PA, 2016 Spring.

- *Teaching assistant & instructional designer*, ADTED 597C, Comparative and international multicultural education, Pennsylvania State University, University Park, PA, 2015 Fall.

- *Teaching assistant & instructional designer*, ADTED 500, Comparative education and development, Pennsylvania State University, University Park, PA, 2014 Spring.

## Supervision
*Post-doctoral scholar*, supervise students work advising in VITAMMINS, Moving Target Tutor, KRK (Theory of Skill Learning and Retention) study tutor project as a post-doctoral scholar at Applied Cognitive Science Lab, College of Information and Technology, Pennsylvania State University, University Park, PA, 2018-2019.

## Service
### Editorial Work & Reviewer
- Performance Improvement Quarterly 2018, 2019
- Industrial and Commercial Training 2019
- Knowledge Management Research & Practice 2018

### Academic service & internships
- *AHRD Enrollment Analysis,* Academy of Human Resource Development in America, 2019.
- *Communication officer*, Korean Academy of Human Resource Development in America, 2015-2016.
- *Proceedings editor's assistant,* Academy of human resource development international conference, 2010-2011.
- *Webmaster / newsletter editor*, student chapter of society of human resource management, Indiana State University, 2009-2010.
- *Database administrator,* Workforce Education and Development student performance database development project, Pennsylvania State University, 2014.
- *Seminar coordinator,* Brownbag seminar: Raspberry Pi at college of education, Pennsylvania State University, Pennsylvania State University, 2013.
- *Seminar coordinator,* Bootcamp R at the College of Education, Pennsylvania State University, PA, 2013.
- *Intern,* Indiana State University Career Center, Terre Haute, IN, 2010.
- *Staff,* Independent digital movie making group, 118system, Korea, 2004-2005.
- *Intern,* Korea Electronics Technology Institute, Korea, 1999-2000.
- *Military service*:  *Sergeant*, Korean military, discharged in 2002

## Collaboration in Funded Projects
- *System maintenance & content management,* VITAMMINS Tutor, 2018-2019
	- Project PI & Advisor: Dr. Frank Ritter. 
	- The purpose of the VITAMMINS Tutor is to train military trauma nursing assessment and interventions sponsored by Congressionally Directed Medical Research Program (CDMRP) and the U.S. Army Medical Research Acquisition Activity (CDMRP)and the U.S. Army Medical Research Acquisition Activity (USAMRAA), contract W81XWH-17-C-0002, through and with Charles River Analytics.

- *System maintenance & content management,* Moving Target Tutor, 2018-2019           
	- Project PI & Advisor: Dr. Frank Ritter
	- Sponsored by The Office of Naval Research and MCWL, ONR contracts: N000014-11-1-0275, N000014-10-C-0281, and N000014-11-M-0342 

- *System maintenance & content management,* KRK (Theory of Skill Learning and Retention) Study Maintenance Tutor, 2018-2019
	- Project PI & Advisor: Dr. Frank Ritter                                      |
	- The purpose of this tutor is to teach about the Ben Franklin Radar system and how to trouble shoot its operation.

- *NSF Engineering Research Center for Building Energy System Transformation (BEST ERC)* 
	- Project PI & Advisor: Sez Atamturktur
	- BEST ERC will catalyze fundamental scientific breakthroughs and advanced engineering technologies through work integrating, and thus transforming, the building industry and electric power sectors. We envision a critically important new field in building science, one in which buildings are designed to be distributed nodes of integrated energy generation, storage and utilization capable of coordinated control of onsite energy systems and transactive energy exchange with their neighbors (Geidl and Andersson, 2007; Lee, et al. 2015). 
	- (Pending)


## Product
### Web based tool
*Revision and maintains* on a cognitive based intelligent tutoring tool, D2P2 (Declarative to Procedural 2). <http://acs.ist.psu.edu/d2p2/users/sign_in>                           