---
title: "Publication"
description: |
  Some additional details about the blog
author:
  - name: Chungil Chae
    url: https://chadchae.github.io
    affiliation: Wenzhou-Kean University
    affiliation_url: https://wku.edu.cn/en/faculty/chungil-chae-chad-ph-d/
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  distill::distill_article:
    self_contained: true
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

- All PDF files provided in this page is a draft version. If you want final and clean version, please use link (publisher's link)

## Refereed journals & Indexed Publications

 Year | Index | Publication | Links
---|----|----------------------------------|----
2019 | SCOPUS | Lee, J. H., Kim, S., Chae, C., & Lee, J. (2019) Career growth opportunity on turnover intention: The mediating role of organizational commitment in multinational corporations. International Journal of Human Resource Studies, 9(4), 1-18. doi:10.5296/ijhrs.v9i4.15245 | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2019 | SCOPUS | Passmore, D. L., & Chae, C. (2019). Potential for meta-scientific inquiry to improve the usefulness of HRD research outcomes for practice. Advances in Developing Human Resources, 21(4), 409-420. doi: 10.1177/1523422319870173 | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2019 | SCOPUS | Chae, C., Yoon, S. W., Jo, S., & Han, S. (2019). Structural determinants of human resource development research collaboration networks: A social network analysis of publications between 1990 to 2014. Performance Improvement Quarterly, (Early view). doi: 10.1002/piq.21314 | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2019 | KCI | Lee, J. & Chae, C. (2019). Differences and multi-dimensionality of career success in Korean employees: A topic modeling approach. The Journal of the Korea Contents Association, 19(6), 58-71. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2019 | SSCI | Fusar-Poli, P., Solmi1, M., Brondino, N., Davies, C., Chae, C., Politi, P., Borgwardt S., Lawrie, S. M., Parnas, J., & Mcguire, P. (2019). Transdiagnostic psychiatry: A systematic review. World Psychiatry, 18(2), 192-207. doi:10.1002/wps.20631 | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2019 | SSCI | Han, S, Chae, C, & Passmore, D. L. (2019) Social network analysis and social capital in human resource development research: A practical introduction to R use. Human Resource Development Quarterly, 30(2), 219-243. doi:10.1002/hrdq.21341 | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2019 | SSCI | Han, S., Yoon, D., Suh, B., Li, B., & Chae, C. (2019). Organizational support on knowledge sharing: a moderated mediation model of job characteristics and organizational citizenship behavior. Journal of Knowledge Management, 23(4), 687-704. doi:10.1108/JKM-03-2018-0213 | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2019 | SCOPUS | Passmore, D. L., Baker, R. M. & Chae, C. (2019), Networks for performance. Performance Improvement, 58(3), 20-25. doi:10.1002/pfi.21838 | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2019 | SCOPUS | Passmore, D. L., Chae, C., Borkovskaya, V., Baker, R., & Yim J. (2019). Severity of U.S. construction worker injuries, 2015-2017. E3S Web of Conferences, 97, 06038. doi:10.1051/e3sconf/20199706038 | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2018 | SCOPUS | Passmore, D. L., Chae, C., Kustikova, Y., Baker, R. M., & Yim, J. (2018). An exploration of text mining of narrative reports of injury incidents to assess risk. MATEC Web of Conferences, 251, 06020. doi:10.1051/matecconf/201825106020 | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2018 | KCI | Kim, S., Lee, S., & Chae, C. (2018). Research trends analysis in community network for sustainable RHRD. The Korean Journal of Human Resource Development Quarterly, 20(3), 265-298. doi:10.18211/kjhrdq.2018.20.3.010 | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2018 | SSCI | Han, H., Kim, Y., Kim, S., Cho, Y., & Chae, C. (2018). Looking into the labyrinth of gender inequality: Women physicians in academic medicine. Medical Education, 52(10), 1083-1095. doi:10.1111/medu.13682 | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2017 | SSCI | Han, S., Chae, C., Han, S. J., & Yoon, S. W. (2017). Conceptual organization and identity of HRD: Analyses of evolving definitions, influence, and connections, Human Resource Development Review, 16(3), 294-319. doi: 10.1177/1534484317719822 | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2017 | SCOPUS | Han, S., Chae, C., Macko, P., & Park, W. (2017). How virtual team leaders cope with creativity challenges. European Journal of Training and Development, 41(3), 261-276. doi:EJTD-10-2016-0073 | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2017 | SCOPUS | Park, S., & Chae, C. (2017). Intervention research and its influence on nonintervention research in human resource development. European Journal of Training and Development, 41(5), 410-433. doi:10.1108/EJTD-08-2016-0062 | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2017 | SCOPUS | Bonafini, F. C., Chae, C., Park, E. & Jablokow, K. W. (2017). How much does student engagement with videos and forums in a MOOC affect their achievement? Online Learning, 21(4), 223-240. Retrieved May 16, 2019 from https://www.learntechlib.org/p/183772/ | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2017 | KCI | Chae, C., Han, S., & Kim, J. (2017). Research trends in HRD (2006-2015): A keyword network analysis of articles in AHRD journals. The Korean Journal of Human Resource Development Quarterly, 19(1) 99-127. doi:10.18211/kjhrdq.2017.19.1.004 | [BIB]() [PDF]() [LINK]() [RESOURCE]()



## Conference proceedings, presentations, lectures, workshops, and posters
 Year | Publication | Links
---|---------------------------------|----
2019 | Ritter, F.E., Dixon, M., Chae, C., Garrison, C. (12 October 2019) Declarative to Procedural (D2P) Nursing Trauma Care Tutors. A talk in IST department. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2019 | Ritter, F. E., Stager, S., Brener, M., Chae, C., Weyhrauch, P., Niehaus, J., & McDermott, A. (2019).  Maintenance training under uncertainty: Expanding smart tutoring to support skill learning and retention.  ONR Cognitive Science of Learning Program Review | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2019 | Harford, J., & Chae, C. (2019 August). Helping and hindering factors for inmates meeting the challenges for successful community reentry. Academy of Management Proceedings, 1. https://doi.org/10.5465/AMBPP.2019.13372abstract | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2019 | Yim, J., Chae, C., & Croweder, C. (2019 June). Comparing HRD research semantic structure between U.S. and Korea: A keyword network analysis approach. Presentation at the University Forum for Human Resource Development Annual Conference 2019, Nottingham, England. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2019 | Passmore, D., Park, M., & Chae, C. (2019 June). National accounting for human capital. Presentation at the University Forum for Human Resource Development Annual Conference 2019, Nottingham, England. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2019 | Chae, C. (2019). Using research skills beyond publishing. Presentation for emerging leaders in career and technical education, organization development, and human resource development. Pennsylvania State University, University Park, PA. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2019 | Passmore, D., Chae, C., Borkovskaya, V., Baker, R. M., & Yim, J. (2019 April). Severity of U.S. construction worker injuries, 2015-2017. Paper presented at XXII International Scientific Conference on Advanced in Civil Engineering: Construction - The Formation of Living Environment 2019, Tashkent, Uzbekistan. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2019 | Chae, C. (2019, May). How to organize R projects. Presented at “Starting with R” workshop, Penn State University, University Park, PA. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2019 | Passmore, D., Chae, C., & Baker, R. M. (2019 February). Selectivity and specificity of automated decisions based on p-value calculations: A study design. Poster presented at the 2019 Academy of Human Resource Development International Research Conference in the Americas, Louisville, Kentucky. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2019 | Lee, J., Ahn, J., Chae, C., & Yim, J. (2019 February). A sequence analysis of changing perceptions of decent work among Korean employees. Paper presented at the 2019 Academy of Human Resource Development International Research Conference in the Americas, Louisville, Kentucky. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2018 | Passmore, D., Baker, R. M., & Chae C. (2018 May). Can you trust your algorithm? Paper presented at the EdTech 2018 meeting of the Irish Learning and Technology Association, Carlow, Ireland. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2018 | Suh, B., Li, B., Chae, C., & Han, S. (2018). Organizational support on knowledge sharing: a moderated mediation model of job characteristics and organizational citizenship behavior. Paper presented at the 2017 Academy of Human Resource Development International Research Conference in the Americas, San Antonio, Texas. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2017 | Han, H., Kim, Y., Cho, Y., Chae, C., & Kim, S. (2017). Female physicians’ lived experience in career development in Korean academic medicine. Academy of Management Proceedings, 2017(1), 12200. doi:10.5465/AMBPP.2017.12200abstract | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2017 | Chae, C. (2017). Basic statistics with R. Lecture and workshop at Lao Statistics Bureau sponsored by the Korea Statistics Promotion Institute, Vientiane, Lao People’s Democratic Republic. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2017 | Chae, C. (2017). Open-source research tools and social network analysis for HR/HRD researchers. Presentation sponsored by The Korean Association of Human Resource Development, Chung-Ang University, Korea. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2017 | Chae, C. (2017). Social network analysis for HR/HRD professionals. Workshop presented at the 2017 Academy of Human Resource Development International Research Conference in the Americas, San Antonio, Texas, and sponsored by Korea Academy of Human Resource Development in America. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2017 | Baker, R. M., Baker, F., Passmore, D., & Chae, C. (2017 March) Mixed methods models and use in Academy of Human Resource Development publications. Paper presented at the 2017 Academy of Human Resource Development International Research Conference in the Americas, San Antonio, Texas. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2017 | Chae, C., Al-Khadhuri, J., Passmore, D., Baker, R. M., & Turner, J. (2017 March). Structural model of topics in Academy of Human Resource Development journals, 1990-2015. Paper presented at the 2017 Academy of Human Resource Development International Research Conference in the Americas, San Antonio, Texas. doi:10.6084/m9.figshare.4725577.v1 | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2017 | Chae, C., You, J., Passmore, L., & Baker, R. (2017, March). Social network analysis for human resource development/organization development professionals. Invited pre-conference workshop at the 2017 Academy of Human Resource Development International Research Conference in the Americas, San Antonio, Texas.  | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2017 | Chad, C., Han, S., & Kim, J. (2017). Research trends in adult education (2006-2015): A topic modeling analysis. Paper presented at the meeting of 2017 Adult Education Research Conference, Norman, Oklahoma. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2016 | Chae, C. (2016). A series of lectures and workshops on social network analysis applications in organizational practice. Presented at Universidad ECCI, Bogota, Columbia. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2016 | Kim, Y., Chae, C., Macko, P., Spencer, M., & Cassie, G. (2016, February). Defining workforce development profession and professionals: A content analysis of occupation. Paper presented at the meeting of 2016 Academy of Human Resource Development International Research Conference in the Americas, Jacksonville, Florida. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2016 | Chae, C., Al-Khadhuri, J., Park, W., Harford, J., & Luke, T. (2016, February). Revealing socio-cultural complexity of knowledge sharing motif among Korean and U.S. companies. Paper presented at the meeting of 2016 Academy of Human Resource Development International Research Conference in the Americas, Jacksonville, Florida. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2016 | Chae, C., Yang, H., & Yoon, S. (2016, February). Mapping the HRD knowledge: Keyword network perspective. Paper presented at the meeting of 2016 Academy of Human Resource Development International Research Conference in the Americas, Jacksonville, Florida. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2016 | Chae, C., Al-Khadhuri, J., Yang, H., Park, W (2016, February). A study on research trends in the recent human resource development: Topic modeling approach. Paper presented at the meeting of 2016 Academy of Human Resource Development International Research Conference in the Americas, Jacksonville, Florida. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2015 | Chae, C. (2015). Stochastic social network analysis. Presented at Korean R User Conference, Korea. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2015 | Nicholas, J., Mohammad, H. A., Chae, C., & Mohd, R. (2015, November). School-to-work experiential learning and outcomes for students in career and technical education. Paper presented at the meeting of the Career and Technical Research and Professional Development Conference, New Orleans, Louisiana. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2015 | Chae, C., Yoon, S., & Jo, S. (2015, February). Structural determinants of human resource development research collaboration networks: Social network perspectives. Paper presented at the meeting of 2015 Academy of Human Resource Development International Research Conference in the Americas, St. Louis, Missouri. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2014 | Passmore, D., Baker, R., Chae, C., Fu, I., & Donahue, W. (2014, March). Hybrid course design. Presented at 2014 Symposium for Teaching and Learning with Technology, University Park, PA. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2010 | Eversole, B., & Chae, C. (2010, February). Decision-making styles of CEOs: A new model for human relations problems. Paper presented at 2010 Academy of Human Resource Development International Research Conference in the Americas, Knoxville, Tennessee. | [BIB]() [PDF]() [LINK]() [RESOURCE]()
2009 | Chae, C. (2009). Kirkpatrick’s four levels evaluation model. Presentation to the Wabash Valley SHRM chapter, Terre Haute, IN. | [BIB]() [PDF]() [LINK]() [RESOURCE]()

## Book chapters
 Year | Publication | Links
---|---------------------------------|----
2018 | Chae. C., Suh. B., Han. S., & Han. H. (2018). Enhancing learner-driven informal learning in a virtual practice community: The Massive Open Online Course (MOOC) as a learning solution for professional development. In Keengwe. (Eds.), Handbook of research on digital content, mobile learning and technology integration models in teacher education. (pp. 207-226). Harrisburg, PA: IGI Global. doi:10.4018/978-1-5225-2953-8.ch011 | [BIB]() [PDF]() [LINK]() [RESOURCE]()

## Non-refereed journals
 Year | Publication | Links
---|---------------------------------|----
2015 | Nicholas, J., Chae, C., Mohammed H. A., Zulkifli, R. M., & Passmore, D. (2015). School-to-work revisited: Did work-based learning experiences improve prospects for students in career and technical education? SSRN Electronic Journal. doi:10.2139/ssrn.2703854 | [BIB]() [PDF]() [LINK]() [RESOURCE]()
